baseURL = "http://example.org/"
title = "tommychu"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "tchu"

[params]
    author = "Tommy Chu"
    keywords = "blog,developer,personal,portfolio"
    avatarurl = "https://avatars1.githubusercontent.com/u/51094650?s=460&u=82181d34d5fa861782c81cb0b48c19268540f97e&v=4"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = " "

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/chutified/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in fa-2x"
    weight = 2
    url = "https://linkedin.com/tommy-chu/"

[[params.social]]
    name = "Blog"
    icon = "fab fa-blogger-b fa-2x"
    weight = 3
    url = "TODO blog"

[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 4
    url = "mailto:tommychu2256@gmail.com"

[[params.social]]
    name = "Source code"
    icon = "fas fa-code fa-2x"
    weight = 5
    url = "https://github.com/chutified/portfolio"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.params]
        info = "Back-End Developer and Magician"
        description = "Tommy Chu's personal website"

        # Menu
        [languages.en.menu]

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url  = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"


    [languages.cs]
        languagename = "Čeština"

        [languages.cs.params]
        info = "Back-End Vývojář a Kouzelník"
        description = "Tommy Chu's personal website"

        # Menu
        [languages.cs.menu]

        [[languages.cs.menu.main]]
        name = "O mně"
        weight = 1
        url = "/cs/about/"

        [[languages.cs.menu.main]]
        name = "Blog"
        weight = 2
        url = "/cs/posts/"

        [[languages.cs.menu.main]]
        name = "Projekty"
        weight = 3
        url = "/cs/projects/"
