baseURL: "https://www.chutommy.com"

languageCode: en-us
title: "Tommy Chu"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  gitRepo: https://github.com/chutommy/chutommy.github.io

  enableBlogPost: false
  enableTOC: true

  newsletter:
    enable: true
    provider: mailchimp
    mailchimpURL: https://chutommy.us20.list-manage.com/subscribe/post?u=a1ad669a5cd0d2d47d7ad7e0c&amp;id=ee12979da8

  background: /images/site/bg.png
  logo:
    main: /images/site/main.png
    inverted: /images/site/inverted.png
    favicon: /images/site/main.png