baseURL: "https://www.chutommy.com"

languageCode: en-us
title: "Tommy Chu"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  gitRepo: https://github.com/chutommy/chutommy.github.io

  enableBlogPost: false
  enableTOC: true
  enableTags: true

  background: /images/site/bg.png
  logo:
    main: /images/site/main.png
    inverted: /images/site/inverted.png
    favicon: /images/site/main.png

  features:
    portfolio:
      enable: true
    blog:
      enable: true
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        email: true
#        whatsapp: true
#        tumblr: true
#        pocket: true
#        diaspora: true
#        mastodon: true

    notes:
      enable: true

  footer:
    enable: true
#    Put your template in "layouts/partials" folder of your repo.
#    template: footer.html
    navigation:
      enable: true
    contactMe:
      enable: true
    credentials:
      enable: false

    newsletter:
      enable: false

    disclaimer:
      enable: false