baseURL: "https://chutommy.com/"

languageCode: en-us
title: "Tommy Chu"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  gitRepo: https://github.com/chutommy/chutommy.github.io
  gitBranch: source

  enableBlogPost: true
  enableTOC: true
  enableTags: true

  topNavbar:
    maxVisibleSections: 5

  darkMode:
    provider: darkreader
    enable: false
    default: system

  background: /images/site/bg.jpg
  logo:
    main: /images/site/main.png
    inverted: /images/site/inverted.png
    favicon: /images/site/main.png

  features:
    portfolio:
      enable: true

    blog:
      enable: false
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true

    comment:
      enable: false

    notes:
      enable: true

    analytics:
      enabled: true
      google:
        id: G-KJLLCGTNQQ

  footer:
    enable: true
    navigation:
      enable: true
    contactMe:
      enable: true
    credentials:
      enable: false

    newsletter:
      enable: false

    disclaimer:
      enable: false