baseURL: https://chutommy.github.io

languageCode: en-us
title: "Tommy Chu"
theme: "toha"

# manage languages (https://gohugo.io/content-management/multilingual/)
languages:
  en:
    languageName: English
    weight: 1

# control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# enable global emoji support
enableEmoji: true

# enable analytics
googleAnalytics: "G-0YJQKTMK6Y"

# site parameters
params:
  gitRepo: https://github.com/chutommy/chutommy.github.io/tree/main

  enableBlogPost: false
  enableTOC: true

# provide newsletter configuration
  newsletter:
    enable: false

# site parameters
  background: /images/site/background.png

# The inverted logo will be used in the initial transparent navbar and
# the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/logo-dark.png
    inverted: /images/site/logo-nocirc.png
    favicon: /images/site/logo-fav.png
